name: OpenAI Code Review

on:
    pull_request:
        types: [opened, reopened]

jobs:
    review-pull-request-by-chatgpt:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout pull request branch
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.event.pull_request.head.sha }}

            - name: Fetch to base branch
                run: git fetch origin ${{ github.event.pull_request.base.sha }}:BASE

            - name: Setup Python
                uses: actions/setup-python@v3
                with:
                    python-version: "3.8"
                    architecture: "x64"

            - name: Install Python Library
                run: pip install -r requirements.txt

            - name: Get diff files
                run: git diff --name-only HEAD BASE > _diff_files.txt

            - name: run ChatGPT
                shell: bash
                env:
                    API_KEY: ${{secrets.API_KEY}}
                    ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
                    URL: ${{ github.event.pull_request.html_url }}
                run: |
                    cat _diff_files.txt | while read file_path ; do
                        echo "## summarize updates: ${file_path}"

                        git cat-file -p BASE:${file_path} > _before.txt
                        git cat-file -p HEAD:${file_path} > _after.txt

                        response=$(python sendCodeReview.py "${file_path}" "_before.txt" "_after.txt")
                        echo "${response}" > _body.txt
                        
                        gh pr comment --body-file _body.txt "${URL}"
                    done