name: "PullRequest Code Reviewer for Azure"
on:
    pull_request:
        types: [opened, reopened]
jobs:
    PullRequestCodeReview:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
          - name: Checkout to pull request branch
            uses: actions/checkout@v3
            with:
                ref: ${{ github.event.pull_request.head.sha }}

          - name: PullRequest Code Reviewer for Azure
            uses: ./
            with:
                api-key: ${{ secrets.API_KEY }}
                endpoint-url: ${{ secrets.ENDPOINT_URL }}