name: "PullRequest Code Reviewer for Azure"
on:
    pull_request:
        types: [opened, reopened]
jobs:
    PullRequestCodeReview:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
          - name: Check Files
            shell: bash
            run: ls -la
            
          - name: PullRequest Code Reviewer for Azure
            uses: ./
            with:
                api-key: ${{ secrets.API_KEY }}
                endpoint-url: ${{ secrets.ENDPOINT_URL }}